name: meetup_pipeline
version: "1.0.0"
config-version: 2

profile: meetup_pipeline

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  meetup_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: table