COPY INTO @MEETUP_DE.ANALYTICS.MEETUP_EXPORT_STAGE/events_enriched/run_{{ ts_nodash }}/
FROM MEETUP_DE.ANALYTICS.EVENTS_ENRICHED
FILE_FORMAT = (
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  COMPRESSION = NONE
)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = FALSE;

COPY INTO @MEETUP_DE.ANALYTICS.MEETUP_EXPORT_STAGE/agg_events_by_city/run_{{ ts_nodash }}/
FROM MEETUP_DE.ANALYTICS.AGG_EVENTS_BY_CITY
FILE_FORMAT = (
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  COMPRESSION = NONE
)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = FALSE;

COPY INTO @MEETUP_DE.ANALYTICS.MEETUP_EXPORT_STAGE/agg_groups_by_category/run_{{ ts_nodash }}/
FROM MEETUP_DE.ANALYTICS.AGG_GROUPS_BY_CATEGORY
FILE_FORMAT = (
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  COMPRESSION = NONE
)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = FALSE;

COPY INTO @MEETUP_DE.ANALYTICS.MEETUP_EXPORT_STAGE/agg_groups_by_topic/run_{{ ts_nodash }}/
FROM MEETUP_DE.ANALYTICS.AGG_GROUPS_BY_TOPIC
FILE_FORMAT = (
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  COMPRESSION = NONE
)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = FALSE;

COPY INTO @MEETUP_DE.ANALYTICS.MEETUP_EXPORT_STAGE/agg_events_by_group/run_{{ ts_nodash }}/
FROM MEETUP_DE.ANALYTICS.AGG_EVENTS_BY_GROUP
FILE_FORMAT = (
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  COMPRESSION = NONE
)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = FALSE;