CREATE DATABASE IF NOT EXISTS MEETUP_DE;
USE DATABASE MEETUP_DE;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

CREATE OR REPLACE FILE FORMAT RAW.CSV_FMT
  TYPE = CSV
  PARSE_HEADER = TRUE
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE
  EMPTY_FIELD_AS_NULL = TRUE
  NULL_IF = ('NULL', 'null', '');


CREATE STORAGE INTEGRATION IF NOT EXISTS MEETUP_S3
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = '{{ var.value.SNOWFLAKE_S3_ROLE_ARN }}'
  STORAGE_AWS_EXTERNAL_ID = '{{ var.value.SNOWFLAKE_AWS_EXTERNAL_ID }}'
  STORAGE_ALLOWED_LOCATIONS = (
    's3://meetup-pipeline-2026/landing_normalized/',
    's3://meetup-pipeline-2026/exports/',
    's3://meetup-pipeline-2026/incremental/events/'
  );

CREATE STAGE IF NOT EXISTS RAW.MEETUP_LANDING_STAGE
  URL = 's3://meetup-pipeline-2026/landing_normalized/'
  STORAGE_INTEGRATION = MEETUP_S3
  FILE_FORMAT = RAW.CSV_FMT;

CREATE STAGE IF NOT EXISTS ANALYTICS.MEETUP_EXPORT_STAGE
  URL = 's3://meetup-pipeline-2026/exports/'
  STORAGE_INTEGRATION = MEETUP_S3;

CREATE STAGE IF NOT EXISTS MEETUP_DE.RAW.MEETUP_INCREMENTAL_STAGE
  URL = 's3://meetup-pipeline-2026/incremental/events/'
  STORAGE_INTEGRATION = MEETUP_S3
  FILE_FORMAT = RAW.CSV_FMT;