select
    "event_id" as event_id,
    "event_name" as event_name,
    "description" as event_description,
    "event_url" as event_url,
    "event_status" as event_status,
    "visibility" as event_visibility,
    "created" as event_created,
    "updated" as event_updated,
    "event_time" as event_time,
    "duration" as duration,
    "utc_offset" as utc_offset,
    "headcount" as headcount,
    "rsvp_limit" as rsvp_limit,
    "yes_rsvp_count" as yes_rsvp_count,
    "maybe_rsvp_count" as maybe_rsvp_count,
    "waitlist_count" as waitlist_count,
    "photo_url" as photo_url,
    "why" as why,
    "how_to_find_us" as how_to_find_us,

    "fee.accepts" as fee_accepts,
    "fee.amount" as fee_amount,
    "fee.currency" as fee_currency,
    "fee.description" as fee_description,
    "fee.label" as fee_label,
    "fee.required" as fee_required,

    "rating.average" as event_rating_average,
    "rating.count" as event_rating_count,

    "group_id" as group_id,
    "group.name" as event_group_name,
    "group.urlname" as event_group_urlname,
    "group.join_mode" as event_group_join_mode,
    "group.who" as event_group_who,
    "group.created" as event_group_created,
    "group.group_lat" as event_group_lat,
    "group.group_lon" as event_group_lon,

    "venue_id" as venue_id,
    "venue.name" as venue_name,
    "venue.city" as venue_city,
    "venue.state" as venue_state,
    "venue.country" as venue_country,
    "venue.address_1" as venue_address_1,
    "venue.address_2" as venue_address_2,
    "venue.lat" as venue_lat,
    "venue.lon" as venue_lon,
    "venue.localized_country_name" as venue_localized_country_name,
    "venue.phone" as venue_phone,
    "venue.repinned" as venue_repinned,
    "venue.zip" as venue_zip
from {{ source('raw', 'events') }}